### PR TITLE
Launch file cleanup

### PR DESCRIPTION
**Pull request by petrlmat**
List of changes:

1. Removed unused launch files
- These launch files were either not working, deprecated, or not used. At least I think so. Let me know if anybody was using them.
2. Updated `single_nodelet.launch`
- Can be included in other launch files
- Not namespaced
- Can be run in nodelet manager or standalone
- Can be run with camera viewer, calibration, and rectification
- Loads default device id from `~/.bashrc`
- Looks for calibration files in `mrs_uav_general`
- All parameters changeable by arguments
3. Added `example.launch`
- Shows how to include the `single_nodelet.launch` into a custom launch file
- Adds `uav_name` namespace
- Lists most often changed parameters

I don't know about the `single_nodelet_hw_trig.launch`. Is somebody using it or can I delete it? What is the difference from the default `single_nodelet.launch`? @bednarhonza @DanHert

### CODE REVIEW

**Comment by petrlmat** [comment]
I would prefer not to add more launch files to this package. We can keep only the `single_nodelet.launch` and everyone can include it from their launch file in their repository as shown in the `example.launch`.

**Comment by petrlmat** [comment]
Removed `single_nodelet_hw_trig.launch`. The difference from the default launch file was the trigger mode `ctm`, which can be overwritten by a custom launch file.

**Comment by klaxalk** [comment]
Thanks for the great work! That is exactly what I wished for :-). Merge as you wish.

**Review by matemat13 — APPROVED** [review]
fine with me

**Pull request merged**
